spring:
  application:
    name: Notiefy-toplist-client
  rabbitmq:
    host: localhost
    password: guest
    username: guest
    port: 5672
    virtual-host: /

server:
  port: 8083

rabbitmq:
  song-count:
    queue: songCount
  song-analytics:
    queue: songAnalytics
    exchange: songAnalyticsExchange
    key: song.analytics